services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        container_name: mtaylorsherwood-dev
        image: mtaylorsherwood-dev
        ports:
            - "1986:80"
        volumes:
            - .:/var/www/html
        links:
            - db
    db:
        image: postgres
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: laravel-password
            POSTGRES_USER: laravel
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
