services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        container_name: mtaylorsherwood-dev
        image: mtaylorsherwood-dev
        ports:
            - "1986:80"
        volumes:
            - .:/var/www/html
            - vendor:/var/www/html/vendor
            - node_modules:/var/www/html/node_modules
        depends_on:
            - db
    db:
        image: mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mtaylorsherwood-dev-root
            MYSQL_DATABASE: mtaylorsherwood-dev
            MYSQL_USER: mtaylorsherwood-dev
            MYSQL_PASSWORD: mtaylorsherwood-dev-password
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
    vendor:
    node_modules:
