services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        container_name: mtaylorsherwood-dev
        image: mtaylorsherwood-dev
        ports:
            - "8003:80"
        volumes:
            -   .:/var/www/html
        links:
            -   db
    db:
        image: mysql:8.4.2
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mtaylorsherwood-dev-root
            MYSQL_DATABASE: mtaylorsherwood-dev
            MYSQL_USER: mtaylorsherwood-dev
            MYSQL_PASSWORD: mtaylorsherwood-dev-password
